import argparse
import os

import numpy as np

import autosklearn
import autosklearn.data
import autosklearn.data.data_manager
import autosklearn.models.evaluator
from ParamSklearn.classification import ParamSklearnClassifier

parser = argparse.ArgumentParser()
parser.add_argument('input')
parser.add_argument('output')
args = parser.parse_args()

input = args.input
dataset = 'jasmine'
output = args.output

D = autosklearn.data.data_manager.DataManager(dataset, input)
X = D.data['X_train']
y = D.data['Y_train']
X_valid = D.data['X_valid']
X_test = D.data['X_test']

# Subset of features found with RFE. Feature with least importance in sklearn
#  RF removed. Afterwards, trained RF on remaining features with 5CV. In the
# end, choose feature set with lowest error
features = [6, 8, 10, 12, 16, 18, 20, 21, 22, 25, 26, 33, 37, 38, 39, 40, 42,
            44, 46, 47, 52, 55, 56, 58, 62, 77, 78, 79, 82, 85, 91, 92, 94, 96,
            101, 104, 106, 108, 110, 119, 122, 125, 130, 131, 133, 137, 139,
            140, 141]

X = X[:, features]
X_valid = X_valid[:, features]
X_test = X_test[:, features]

# Weights of the ensemble members as determined by Ensemble Selection
weights = np.array([0.140000, 0.120000, 0.080000, 0.060000, 0.040000, 0.040000,
                    0.040000, 0.040000, 0.040000, 0.040000, 0.020000, 0.020000,
                    0.020000, 0.020000, 0.020000, 0.020000, 0.020000, 0.020000,
                    0.020000, 0.020000, 0.020000, 0.020000, 0.020000, 0.020000,
                    0.020000, 0.020000, 0.020000, 0.020000])

# Ensemble members found by SMAC
configurations = [
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'median',
     'preprocessor': 'select_percentile_classification',
     'random_forest:bootstrap': 'True',
     'random_forest:criterion': 'gini',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '1.58545644982',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '3.0',
     'random_forest:min_samples_split': '2.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_percentile_classification:percentile': '39.9235093683',
     'select_percentile_classification:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'most_frequent',
     'preprocessor': 'select_rates',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '0.6715305958',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '4.0',
     'random_forest:min_samples_split': '3.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'standard',
     'select_rates:alpha': '0.486873466534',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_percentile_classification',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'gini',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '1.82773631717',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '3.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_percentile_classification:percentile': '50.0',
     'select_percentile_classification:score_func': 'chi2'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '832.0',
     'fast_ica:whiten': 'False',
     'imputation:strategy': 'median',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'gini',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.93148979051',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '5.0',
     'random_forest:min_samples_split': '7.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_percentile_classification',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '1.79654377812',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '1.0',
     'random_forest:min_samples_split': '6.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_percentile_classification:percentile': '50.0',
     'select_percentile_classification:score_func': 'chi2'},
    {'balancing:strategy': 'weighting',
     'classifier': 'extra_trees',
     'extra_trees:bootstrap': 'False',
     'extra_trees:criterion': 'entropy',
     'extra_trees:max_depth': 'None',
     'extra_trees:max_features': '1.81061189332',
     'extra_trees:min_samples_leaf': '1.0',
     'extra_trees:min_samples_split': '3.0',
     'extra_trees:n_estimators': '100.0',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_rates',
     'rescaling:strategy': 'none',
     'select_rates:alpha': '0.201722721361',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'extra_trees',
     'extra_trees:bootstrap': 'False',
     'extra_trees:criterion': 'gini',
     'extra_trees:max_depth': 'None',
     'extra_trees:max_features': '1.76442905847',
     'extra_trees:min_samples_leaf': '4.0',
     'extra_trees:min_samples_split': '6.0',
     'extra_trees:n_estimators': '100.0',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_rates',
     'rescaling:strategy': 'min/max',
     'select_rates:alpha': '0.113572172949',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'median',
     'preprocessor': 'select_rates',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.87832643035',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '1.0',
     'random_forest:min_samples_split': '19.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_rates:alpha': '0.110716868617',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'extra_trees',
     'extra_trees:bootstrap': 'True',
     'extra_trees:criterion': 'entropy',
     'extra_trees:max_depth': 'None',
     'extra_trees:max_features': '3.23138088334',
     'extra_trees:min_samples_leaf': '3.0',
     'extra_trees:min_samples_split': '6.0',
     'extra_trees:n_estimators': '100.0',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_percentile_classification',
     'rescaling:strategy': 'min/max',
     'select_percentile_classification:percentile': '45.1994111355',
     'select_percentile_classification:score_func': 'chi2'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '509.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'mean',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.2727882732',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '12.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'median',
     'preprocessor': 'select_percentile_classification',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.32162402484',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '1.0',
     'random_forest:min_samples_split': '12.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_percentile_classification:percentile': '41.8671636453',
     'select_percentile_classification:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '690.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'mean',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.3355464987',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '11.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'median',
     'preprocessor': 'select_rates',
     'random_forest:bootstrap': 'True',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '4.2700093411',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '4.0',
     'random_forest:min_samples_split': '11.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_rates:alpha': '0.294021193269',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '613.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'median',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '1.8000767552',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '7.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '661.0',
     'fast_ica:whiten': 'False',
     'imputation:strategy': 'mean',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.23424202393',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '3.0',
     'random_forest:min_samples_split': '10.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '606.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'median',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '1.82743208676',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '3.0',
     'random_forest:min_samples_split': '11.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'extra_trees',
     'extra_trees:bootstrap': 'True',
     'extra_trees:criterion': 'gini',
     'extra_trees:max_depth': 'None',
     'extra_trees:max_features': '4.32850858484',
     'extra_trees:min_samples_leaf': '3.0',
     'extra_trees:min_samples_split': '5.0',
     'extra_trees:n_estimators': '100.0',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_rates',
     'rescaling:strategy': 'min/max',
     'select_rates:alpha': '0.118453703147',
     'select_rates:mode': 'fpr',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '1098.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'most_frequent',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '4.83031750621',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '1.0',
     'random_forest:min_samples_split': '15.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'imputation:strategy': 'median',
     'preprocessor': 'select_rates',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'gini',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '3.52038352463',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '4.0',
     'random_forest:min_samples_split': '4.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'standard',
     'select_rates:alpha': '0.441859738474',
     'select_rates:mode': 'fpr',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '743.0',
     'fast_ica:whiten': 'False',
     'imputation:strategy': 'median',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.37406180812',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '17.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '531.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'mean',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.38993786345',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '4.0',
     'random_forest:min_samples_split': '16.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'extra_trees',
     'extra_trees:bootstrap': 'False',
     'extra_trees:criterion': 'entropy',
     'extra_trees:max_depth': 'None',
     'extra_trees:max_features': '1.60284209578',
     'extra_trees:min_samples_leaf': '4.0',
     'extra_trees:min_samples_split': '10.0',
     'extra_trees:n_estimators': '100.0',
     'imputation:strategy': 'most_frequent',
     'preprocessor': 'select_rates',
     'rescaling:strategy': 'min/max',
     'select_rates:alpha': '0.486662334462',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'chi2'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '1082.0',
     'fast_ica:whiten': 'False',
     'imputation:strategy': 'median',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '1.47545539014',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '15.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '985.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'most_frequent',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'gini',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '3.87640604363',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '2.0',
     'random_forest:min_samples_split': '11.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'weighting',
     'classifier': 'gradient_boosting',
     'gradient_boosting:learning_rate': '0.236639577539',
     'gradient_boosting:max_depth': '5.0',
     'gradient_boosting:max_features': '1.94802938969',
     'gradient_boosting:min_samples_leaf': '3.0',
     'gradient_boosting:min_samples_split': '4.0',
     'gradient_boosting:n_estimators': '100.0',
     'gradient_boosting:subsample': '0.499388145134',
     'imputation:strategy': 'most_frequent',
     'preprocessor': 'select_rates',
     'rescaling:strategy': 'min/max',
     'select_rates:alpha': '0.078631031495',
     'select_rates:mode': 'fwe',
     'select_rates:score_func': 'f_classif'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'imputation:strategy': 'mean',
     'preprocessor': 'select_percentile_classification',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'gini',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.89271865035',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '9.0',
     'random_forest:min_samples_split': '2.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max',
     'select_percentile_classification:percentile': '58.6633457276',
     'select_percentile_classification:score_func': 'chi2'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '1299.0',
     'fast_ica:whiten': 'False',
     'imputation:strategy': 'mean',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '4.38103060363',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '3.0',
     'random_forest:min_samples_split': '2.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
    {'balancing:strategy': 'none',
     'classifier': 'random_forest',
     'fast_ica:algorithm': 'deflation',
     'fast_ica:fun': 'logcosh',
     'fast_ica:n_components': '1653.0',
     'fast_ica:whiten': 'True',
     'imputation:strategy': 'median',
     'preprocessor': 'fast_ica',
     'random_forest:bootstrap': 'False',
     'random_forest:criterion': 'entropy',
     'random_forest:max_depth': 'None',
     'random_forest:max_features': '2.58731902957',
     'random_forest:max_leaf_nodes': 'None',
     'random_forest:min_samples_leaf': '8.0',
     'random_forest:min_samples_split': '19.0',
     'random_forest:n_estimators': '100.0',
     'rescaling:strategy': 'min/max'},
]

classifiers = []
predictions_valid = []
predictions_test = []

# Make predictions and weight them
for weight, configuration in zip(weights, configurations):
    for param in configuration:
        try:
            configuration[param] = int(configuration[param])
        except Exception:
            try:
                configuration[param] = float(configuration[param])
            except Exception:
                pass

    classifier = ParamSklearnClassifier(configuration, 1)
    classifiers.append(classifier)
    try:
        classifier.fit(X.copy(), y.copy())
        predictions_valid.append(classifier.predict_proba(X_valid.copy()) * weight)
        predictions_test.append(classifier.predict_proba(X_test.copy()) * weight)
    except Exception as e:
        print e
        print configuration

# Output the predictions
for name, predictions in [('valid', predictions_valid),
                          ('test', predictions_test)]:
    predictions = np.array(predictions)
    predictions = np.sum(predictions, axis=0)
    predictions = predictions[:, 1].reshape((-1, 1))

    filepath = os.path.join(output, '%s_%s_000.predict' % (dataset, name))
    np.savetxt(filepath, predictions, delimiter=' ')